import { getOwner, resetOwner, restoreOwner } from "evolu";
import { pipe } from "fp-ts/function";
import { FC, useEffect, useState } from "react";
import { useIntl } from "react-intl";
import { Button, ButtonProps } from "../components/Button";
import { Dialog } from "../components/Dialog";
import { Layout } from "../components/Layout";
import { PageTitle } from "../components/PageTitle";
import { Text, View } from "../components/styled";
import { T } from "../components/T";
import { useQuery } from "../lib/db";
import { clearAllLocalStorageKeys } from "../lib/localStorage";

const BigButtonWithDescription: FC<
  ButtonProps & { title: string; description: string }
> = ({ title, description, ...props }) => {
  return (
    <View className="mb-3">
      <View className="mb-1 flex-row">
        <Button {...props}>
          <T v="bb">{title}</T>
        </Button>
      </View>
      <View className="px-2">
        <T v="p">{description}</T>
      </View>
    </View>
  );
};

const DownloadLink = () => {
  const intl = useIntl();
  const { rows, isLoaded } = useQuery((db) =>
    // TODO: Add all tables.
    db.selectFrom("evolu").selectAll().orderBy("createdAt")
  );
  const [url, setUrl] = useState<string | null>(null);

  useEffect(() => {
    if (!isLoaded) return;
    pipe(
      JSON.stringify(rows),
      (json) => new Blob([json], { type: "application/json" }),
      (blob) => URL.createObjectURL(blob),
      setUrl
    );
  }, [isLoaded, rows]);

  const fileName = intl.formatMessage({
    defaultMessage: "backup.json",
    id: "y1unJo",
  });

  return (
    <T v="p">
      {!url ? (
        intl.formatMessage({ defaultMessage: "Preparing…", id: "Ob8gKI" })
      ) : (
        <Text
          // @ts-expect-errors RNfW
          href={url}
          hrefAttrs={{ target: "blank", download: fileName }}
          className="rounded underline focus:outline-none focus-visible:ring-2"
        >
          {fileName}
        </Text>
      )}
    </T>
  );
};

const Settings = () => {
  const intl = useIntl();
  const [mnemonic, setMnemonic] = useState<string | null>(null);
  const [download, setDownload] = useState(false);

  return (
    <>
      <PageTitle title="Settings" />
      <Layout>
        <T v="h1">
          {intl.formatMessage({ defaultMessage: "Settings", id: "D3idYv" })}
        </T>
        <BigButtonWithDescription
          title={intl.formatMessage({
            defaultMessage: "Show Mnemonic",
            id: "/Kjmsc",
          })}
          description={intl.formatMessage({
            defaultMessage:
              "A Mnemonic is a strong and human-readable password generated by your device.",
            id: "GteWll",
          })}
          onPress={() => {
            getOwner().then((owner) => {
              setMnemonic(mnemonic == null ? owner.mnemonic : null);
            });
          }}
        />
        {mnemonic && (
          <Dialog
            title={intl.formatMessage({
              defaultMessage: "Your Mnemonic",
              id: "mwh5gw",
            })}
            onRequestClose={() => setMnemonic(null)}
          >
            <T v="p">{mnemonic}</T>
          </Dialog>
        )}
        <BigButtonWithDescription
          title={intl.formatMessage({
            defaultMessage: "Restore Data",
            id: "fmvzdQ",
          })}
          description={intl.formatMessage({
            defaultMessage:
              "Open this page on a different device and use your mnemonic to restore your data.",
            id: "6RggLU",
          })}
          onPress={() => {
            const mnemonic = prompt(
              intl.formatMessage({
                defaultMessage: "Your Mnemonic",
                id: "mwh5gw",
              })
            );
            if (mnemonic == null) return;
            const either = restoreOwner(mnemonic);
            if (either._tag === "Left")
              alert(JSON.stringify(either.left, null, 2));
          }}
        />
        <BigButtonWithDescription
          title={intl.formatMessage({
            defaultMessage: "Download Data",
            id: "5jKtTm",
          })}
          description={intl.formatMessage({
            defaultMessage: "Download your data as JSON.",
            id: "bAR4Hi",
          })}
          onPress={() => {
            setDownload(true);
          }}
        />
        {download && (
          <Dialog
            title={intl.formatMessage({
              defaultMessage: "Your Data",
              id: "jqRQnw",
            })}
            onRequestClose={() => setDownload(false)}
          >
            <DownloadLink />
          </Dialog>
        )}
        <BigButtonWithDescription
          title={intl.formatMessage({
            defaultMessage: "Delete Data",
            id: "u0BHMY",
          })}
          description={intl.formatMessage({
            defaultMessage: "Delete all your data from this device.",
            id: "B7tjpq",
          })}
          onPress={() => {
            if (
              confirm(
                intl.formatMessage({
                  defaultMessage:
                    "Are you sure? It will delete all your local data.",
                  id: "gUiimf",
                })
              )
            ) {
              clearAllLocalStorageKeys();
              resetOwner();
            }
          }}
        />
      </Layout>
    </>
  );
};

export default Settings;
