import { getOwner, resetOwner, restoreOwner } from "evolu";
import { useState } from "react";
import { useIntl } from "react-intl";
import { Heading } from "../components/Heading";
import { Layout } from "../components/Layout";
import { Modal } from "../components/Modal";
import { PageTitle } from "../components/PageTitle";
import { Paragraph } from "../components/Paragraph";
import { TextInput, View } from "../components/styled";
import { TextButton } from "../components/TextButton";
import { useQuery } from "../lib/db";
import { clearAllLocalStorageKeys } from "../lib/localStorage";

const Download = () => {
  const intl = useIntl();
  const { rows } = useQuery((db) =>
    db.selectFrom("evolu").selectAll().orderBy("createdAt")
  );

  return (
    <View className="w-80">
      <Heading>
        {intl.formatMessage({ defaultMessage: "Your Data", id: "jqRQnw" })}
      </Heading>
      <TextInput
        multiline
        numberOfLines={20}
        value={JSON.stringify(rows, null, 2)}
        // className="h-72"
      />
    </View>
  );
};

const Settings = () => {
  const intl = useIntl();
  const [mnemonic, setMnemonic] = useState<string | null>(null);
  const [download, setDownload] = useState(false);

  return (
    <>
      <PageTitle title="Settings" />
      <Layout>
        <Heading level={1}>
          {intl.formatMessage({ defaultMessage: "Settings", id: "D3idYv" })}
        </Heading>
        <TextButton
          title={intl.formatMessage({
            defaultMessage: "Show Mnemonic",
            id: "/Kjmsc",
          })}
          description={intl.formatMessage({
            defaultMessage:
              "A Mnemonic is a strong and human-readable password generated by your device.",
            id: "GteWll",
          })}
          onPress={() => {
            getOwner().then((owner) => {
              setMnemonic(mnemonic == null ? owner.mnemonic : null);
            });
          }}
        />
        <TextButton
          title={intl.formatMessage({
            defaultMessage: "Restore Data",
            id: "fmvzdQ",
          })}
          description={intl.formatMessage({
            defaultMessage:
              "Open this page on a different device and use your mnemonic to restore your data.",
            id: "6RggLU",
          })}
          onPress={() => {
            const mnemonic = prompt(
              intl.formatMessage({
                defaultMessage: "Your Mnemonic",
                id: "mwh5gw",
              })
            );
            if (mnemonic == null) return;
            const either = restoreOwner(mnemonic);
            if (either._tag === "Left")
              alert(JSON.stringify(either.left, null, 2));
          }}
        />
        <TextButton
          title={intl.formatMessage({
            defaultMessage: "Download Data",
            id: "5jKtTm",
          })}
          description={intl.formatMessage({
            defaultMessage: "Download your data as JSON.",
            id: "bAR4Hi",
          })}
          onPress={() => {
            setDownload(true);
          }}
        />
        <TextButton
          title={intl.formatMessage({
            defaultMessage: "Delete Data",
            id: "u0BHMY",
          })}
          description={intl.formatMessage({
            defaultMessage: "Delete all your data from this device.",
            id: "B7tjpq",
          })}
          onPress={() => {
            if (
              confirm(
                intl.formatMessage({
                  defaultMessage:
                    "Are you sure? It will delete all your local data.",
                  id: "gUiimf",
                })
              )
            ) {
              clearAllLocalStorageKeys();
              resetOwner();
            }
          }}
        />
      </Layout>
      {mnemonic && (
        <Modal centerContent onRequestClose={() => setMnemonic(null)}>
          <Heading level={2}>
            {intl.formatMessage({
              defaultMessage: "Your Mnemonic",
              id: "mwh5gw",
            })}
          </Heading>
          <Paragraph>{mnemonic}</Paragraph>
        </Modal>
      )}
      {download && (
        <Modal centerContent onRequestClose={() => setDownload(false)}>
          <Download />
        </Modal>
      )}
    </>
  );
};

export default Settings;
